V2.0.0

diff --git a/assemble b/assemble
--- a/assemble
+++ b/assemble
@@ -1,16 +1,22 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-VERSION="1.0.1"
-INPUT=""
+VERSION="2.0.0"
+INPUT=
 FINPUT=false
 HEXFLAGS="-X"
-MODE=64
-while getopts "ef:rx" flag; do
+PREFIX=
+MODE=
+T_ASSEMBLER="fasm \\if \\of"
+CONFIG=true
+
+
+while getopts "a:cf:hp:x:" flag; do
         case $flag in
-        e)      MODE=32;;
-        f)      if [ "$INPUT" != "" ]; then
-                        echo "Error: file input and string input are both used."
-                        exit
+	a) 	T_ASSEMBLER="$OPTARG";;
+	c)	CONFIG=false;;
+        f)      if [[ $FINPUT = true ]]; then
+                        echo "Error: Multiple file input."
+                        exit 1
                 fi
                 INPUT="$OPTARG"
                 FINPUT=true;;
@@ -20,31 +26,56 @@ while getopts "ef:rx" flag; do
                 echo "  the assembled values of assembly expressions."
                 echo "\n  Usage: assemble {OPTIONS}"
                 echo "\nOptions:"
-                echo "  -e"
-                echo "    Sets assembler to 32 bit mode."
+		echo "  -a <format text>"
+		echo "    Replacing '\\if' with the input argument and '\\of' with the output"
+		echo "    argument set the assembler."
+		echo "  -c"
+		echo "    Disables config loading."
                 echo "  -f <file>"
                 echo "    Reads input from file instead of user input."
-                echo "  -r"
-                echo "    Sets assembler to 64 bit mode (default)."
-                echo "  -x"
-                echo "    Sets assembler to 16 bit mode."
-                ;;
-        r)      MODE=64;;
-        x)      MODE=16;;
+                echo "  -p <prefix>"
+                echo "    Prefix the output with the supplied prefix."
+		echo "\nConfig file:"
+		echo "  The config file is to be stored at \$HOME/.assemble.config, and in the case"
+		echo "  that it does, the following values may be set:"
+		echo "    T_ASSEMBLER=x    Sets the value of -a."
+		echo "    PREFIX=x         Sets the value of -p."
+		echo "  Note that \$MODE may be used at any point in the config."
+		;;
+        p)      PREFIX="$OPTARG";;
+	x)	MODE="$OPTARG";;
         esac
 done
 
-if [ "$INPUT" = "" ]; then
-        echo "Enter assembly (CTR-D to conitnue):"
-        echo "use${MODE}" >> /tmp/.assemble.input
-        cat >> /tmp/.assemble.input
-        fasm /tmp/.assemble.input /tmp/.assemble.output &&\
-        hexdump $HEXFLAGS /tmp/.assemble.output
-        rm -f /tmp/.assemble.input /tmp/.assemble.output
-else
-        if [ "$FINPUT" = true ]; then
-                fasm "$INPUT" /tmp/.assemble.output &&\
-                hexdump $HEXFLAGS /tmp/.assemble.output
-                rm -f /tmp/.assemble.output
-        fi
+if [[ $CONFIG = true && -f "$HOME/.assemble.config" ]]; then
+	. ~/.assemble.config
 fi
+
+rm -f /tmp/.assemble.input /tmp/.assemble.output
+printf "$PREFIX" >> /tmp/.assemble.input
+if [[ $FINPUT = false ]]; then
+        echo "Enter assembly (CTR-D to conitnue):"
+        cat >> /tmp/.assemble.input
+else
+	cat "$INPUT" >> /tmp/.assemble.input
+fi
+
+OIFS=$IFS
+IFS=' '
+ASSEMBLER=""
+for readin in $T_ASSEMBLER
+do
+	if [[ "$readin" = "\\if" ]]; then
+		ASSEMBLER="$ASSEMBLER /tmp/.assemble.input"
+	elif [[ "$readin" = "\\of" ]]; then
+		ASSEMBLER="$ASSEMBLER /tmp/.assemble.output"
+	else
+		ASSEMBLER="$ASSEMBLER $readin"
+	fi
+done
+IFS=$OIFS
+
+$ASSEMBLER
+
+hexdump $HEXFLAGS /tmp/.assemble.output
+rm -f /tmp/.assemble.input /tmp/.assemble.output
